apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-os-server
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi-os-server
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "unifi.example.com"
    secretName: tls-secret
  rules:
  - host: unifi.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi-os-server-webui-svc
            port:
              number: 443
